<?php
$title='Appointments'; require_once __DIR__.'/../includes/functions.php'; requireAdmin(); $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();$id=(int)$_POST['id'];$status=$_POST['status'];$allowed=['pending','confirmed','completed','cancelled','no_show'];if(in_array($status,$allowed,true)){ $stmt=$pdo->prepare("UPDATE appointments SET status=? WHERE id=?");$stmt->execute([$status,$id]); flash('success','Appointment updated.');} redirect('appointments.php');}
$rows=$pdo->query("SELECT a.id,a.start_at,a.end_at,a.status,a.notes,c.name customer,c.phone,s.name service,b.name barber,p.amount,p.status payment_status FROM appointments a JOIN customers c ON c.id=a.customer_id JOIN services s ON s.id=a.service_id JOIN barbers b ON b.id=a.barber_id LEFT JOIN payments p ON p.appointment_id=a.id ORDER BY a.start_at DESC")->fetchAll();
require __DIR__.'/../includes/header.php';
?>
<div class="card"><h2>Appointments</h2><div class="table-wrap"><table class="table"><tr><th>When</th><th>Customer</th><th>Service</th><th>Barber</th><th>Status</th><th>Payment</th><th>Action</th></tr>
<?php foreach($rows as $r): ?><tr><td><?=e(date('d M Y H:i',strtotime($r['start_at'])))?></td><td><?=e($r['customer'])?><br><span class="muted"><?=e($r['phone'])?></span></td><td><?=e($r['service'])?></td><td><?=e($r['barber'])?></td><td><span class="badge <?=e($r['status'])?>"><?=e($r['status'])?></span></td><td>R<?=number_format((float)$r['amount'],2)?> · <?=e($r['payment_status'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(csrfToken())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status" onchange="this.form.submit()"><?php foreach(['pending','confirmed','completed','cancelled','no_show'] as $s): ?><option <?= $r['status']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></form></td></tr><?php endforeach; ?></table></div></div>
<?php require __DIR__.'/../includes/footer.php'; ?>
